name: Make Linux releases
on:
  workflow_dispatch:
    inputs:
      sbt_ver:
        description: the version of sbt to release
        required: true
        default: 1.4.x
      dist_patchver:
        description: patch version if needed
        required: true
        default: 0

jobs:
  linux-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: temurin
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M
      SBT_VER: ${{ github.event.inputs.sbt_ver }}
      DIST_PATCHVER: ${{ github.event.inputs.dist_patchver }}
    steps:
    - name: Checkout sbt/sbt-dist
      uses: actions/checkout@v4
    - name: Checkout sbt/sbt
      uses: actions/checkout@v4
      with:
        repository: sbt/sbt
        ref: v${{ github.event.inputs.sbt_ver }}
        path: sbt
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
    - uses: sbt/setup-sbt@v1
    - name: Build
      shell: bash
      run: |
        mode=linuxrelease bin/run-ci.sh
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
