name: Sonatype IO 1.x release
on:
  workflow_dispatch:
    inputs:
      io_ver:
        description: the version of sbt to release
        required: true
        default: 1.12.x

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M
      IO_VER: ${{ github.event.inputs.io_ver }}
    steps:
    - name: Checkout sbt/sbt-dist
      uses: actions/checkout@v7
    - name: Checkout sbt/io
      uses: actions/checkout@v7
      with:
        repository: sbt/io
        ref: v${{ github.event.inputs.io_ver }}
        path: io
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
    - uses: sbt/setup-sbt@v1
    - name: Build
      shell: bash
      run: |
        mode=sonatype_io bin/run-ci.sh
      env:
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        RELEASE_COMMAND: "+publishSigned sonaUpload"
